version: '3.8'

services:
  web:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    container_name: fastapi_app
    ports:
      - "80:80"
    volumes:
      - ./api:/app
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fastapi
      MYSQL_ROOT_PASSWORD: fastapi_password
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=fastapi_password
      - UPLOAD_LIMIT=2048M

    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - /sessions

    tty: true

volumes:
  db-data:
    external: false